// <auto-generated />
using FrasesMAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrasesMAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FrasesMAPI.Models.FM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("frase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("sentimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("ID");

                    b.ToTable("TB_frasesM", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            autor = "Donald Trump",
                            frase = "Não deixe que a tristeza atrapalhe seus sonhos e objetivos...",
                            sentimento = "Tristeza"
                        },
                        new
                        {
                            ID = 2,
                            autor = "Charlie Chaplin",
                            frase = "A vida é maravilhosa se não se tem medo dela.",
                            sentimento = "Medo"
                        },
                        new
                        {
                            ID = 3,
                            autor = "Cartola",
                            frase = "A sorrir eu pretendo levar a vida..",
                            sentimento = "Felicidade"
                        },
                        new
                        {
                            ID = 4,
                            autor = "augusto Cury",
                            frase = "Não tenha medo do caminho, tenha medo de não caminhar",
                            sentimento = "Ansiedade"
                        },
                        new
                        {
                            ID = 5,
                            autor = "Bob Marley",
                            frase = "Saudade é um sentimento que, quando não cabe no coração, escorre pelos olhos.",
                            sentimento = "Saudade"
                        },
                        new
                        {
                            ID = 6,
                            autor = "Chico Xavier",
                            frase = "A desilusão é a visita da verdade.",
                            sentimento = "Decepção"
                        },
                        new
                        {
                            ID = 7,
                            autor = "Shakespeare",
                            frase = "A raiva é um veneno que bebemos esperando que os outros morram.",
                            sentimento = "Raiva"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
